export * from "./taxonomia.ts";
export * from "./tipos.ts";
export * from "./normalizar/texto.ts";
export * from "./normalizar/data.ts";
export * from "./normalizar/montante.ts";
export * from "./identidade.ts";
export * from "./diferencas.ts";
export * from "./varrimento.ts";
export * from "./correspondencia.ts";
